name: Build Android 🐸

on:
  push:
    branches:
      - 'main'
      
jobs:
    build:
        name: Android Build
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Setup Bun CLI
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest

            - name: Install dependencies
              run:  bun install --network-timeout 300000
            
            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v1

            - name: Cache Gradle Dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
                  restore-keys: ${{ runner.os }}-gradle-caches-

            - name: Make Gradlew Executable
              run: cd android && chmod +x ./gradlew

            - name: Build Android Release
              run: cd android && ./gradlew clean && ./gradlew app:assembleRelease

            - name: Sign APK
              id: sign_app
              uses: r0adkll/sign-android-release@v1
              with:
                releaseDirectory: ${{ github.workspace}}/app-name/android/app/build/outputs/apk/release
                signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
                alias: ${{ secrets.ANDROID_SIGNING_ALIAS }}
                keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
                keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

            - name: Upload APK
              id: uploadArtifact
              uses: actions/upload-artifact@v3
              with:
                name: RN_Actions.aab
                path: ${{steps.sign_app.outputs.signedReleaseFile}}
            
            - name: Install Fastlane
              run: gem install fastlane

    publish-to-appcenter:
                    if: ${{ inputs.publish == true }}
                    runs-on: ubuntu-latest
                    needs: build
                    steps:
                      - uses: actions/checkout@v2
                
                      - uses: actions/download-artifact@v3
                        with:
                          name: Timely.aab
                          path: "android/"
                
                      - name: set up JDK 1.8
                        uses: actions/setup-java@v1
                        with:
                          java-version: 1.8
                
                      - name: Upload artifact to App Center
                        uses: wzieba/AppCenter-Github-Action@v1
                        with:
                          appName: paramsinghvc/Timely
                          token: ${{secrets.APPCENTER_TOKEN_ANDROID}}
                          group: UKInternal
                          file: android/app-release.aab
                          notifyTesters: true
                          debug: false
